spring.application.name=iceibank-agencia

server.port=${SERVER_PORT:4093}

jwt.secret=iceibank-chave-secreta-sprint1-2026-chave-compartilhada
jwt.expiration=600000
spring.rabbitmq.addresses=${RABBITMQ_URL}